# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_linear <- function(mt1, mt2, method, rank, limit = -1.0) {
    .Call('_proxyC_cpp_linear', PACKAGE = 'proxyC', mt1, mt2, method, rank, limit)
}

cpp_pair <- function(mt1, mt2, method, rank, limit = -1.0, weight = 1.0) {
    .Call('_proxyC_cpp_pair', PACKAGE = 'proxyC', mt1, mt2, method, rank, limit, weight)
}

